config/routes.rb
Rails.application.routes.draw do

root 'pages#home'

get 'register' => 'users#new'
  # post 'register' => 'users#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


  resources :users
  resources :donations
  resources :distributions
  resources :runners do
    resources :donations
    resources :distributions
  end

  get '/runners/pickup/:donation_id' => 'runners#pickup'
  get '/runners/dropoff/:distr_id' => 'runners#dropoff'

  get 'pages/about'
  get 'pages/help'

  # get 'pages/home'

  # get 'users/new'
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'

  # get 'donations/new'
  # get 'donations/edit'
  # get 'donations/show'
  # get 'donations/index'

  # get 'distributions/new'
  # get 'distributions/edit'
  # get 'distributions/show'
  # get 'distributions/index'

  # get 'runners/new'
  # get 'runners/edit'
  # get 'runners/show'
  # get 'runners/index'

  # get 'sessions/new'
  # get 'sessions/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/distribution.rb
class Distribution < ApplicationRecord
  belongs_to :runner, required: false
  after_validation :geocode

  geocoded_by :dropoff_location

  def full_name
   self.first_name + " " + self.last_name
  end
end

app/controllers/distributions_controller.rb
class DistributionsController < ApplicationController
  before_action :set_distribution, only: [:show, :edit, :update, :destroy]

def new
  @distribution = Distribution.new
  @runners = Runner.all
end

def index
  @runners = Runner.all
  @distributions = Distribution.all
end

def create
  @distribution = Distribution.new(distribution_params)
  if @distribution.save
    msg = "Your distribution has been successfully created"
    p msg
    redirect_to @distribution
  else
      msg = "There was an error in creating your distribution.  Try again"
    p msg
    p @distribution.errors.messages
    render 'new'
  end
end

def edit
end

def show
end

def update
  if @distribution.update(distribution_params)
    p 'Distribution Successfully Updated!'
    redirect_to @distribution
  else
    render 'edit'
  end
end


def destroy
    respond_to do |format|
      format.js
      format.html { p 'html response'; redirect_to root_path }
    end
    @distribution.destroy
end




private

  def set_distribution
      @distribution = Distribution.find(params[:id])
  end

  def distribution_params
    params.require(:distribution).permit(:first_name, :last_name, :email, :phone, :region, :dropoff_location, :distribution, :dropoff_time, :dropoff_date, :runner_id, :donation_id, :password, :password_confirmation)
  end
end

app/helpers/distributions_helper.rb
module DistributionsHelper
  def full_name
    self.first_name + " " + self.last_name
  end
end

app/views/distributions/_form.html.erb
<%= form_for(@distribution) do |f| %>
  First Name:  &nbsp <%= f.text_field :first_name, placeholder: 'First Name', value: current_user.first_name, required: true, edit: false %><br>
  Last Name: &emsp;<%= f.text_field :last_name, placeholder: 'Last Name', value: current_user.last_name, required: true %><br>
  Phone: &emsp;&emsp;&emsp;<%= f.telephone_field :phone, placeholder: 'Phone Number', required: true  %><br>
  Drop Off Date: <%= f.date_field :dropoff_date, required: true  %><br>
  Drop Off Time:  <%= f.time_field :dropoff_time, ampm: true, required: true  %><br>
  Region:&emsp;&emsp;&emsp;&ensp; <%= f.select :region, [['North Queens'], ['South Queens'], ['Uptown'], ['Downtown'], ['Midtown'], ['Harlem'], ['Bronx'],['Staten Island']], :include_blank => true  %><br>
  Drop Off Location: &emsp;&emsp;&emsp;<%= f.text_area :dropoff_location %><br>
  Distribution Description: <%= f.text_area  :distribution, placeholder: 'What do you have to distribute? (Please be specific so runner and donor can porperly prepare)', required: true %><br>
  Runner: <br><br>

    <%= f.submit %>
<% end %>

app/views/distributions/destroy.js.erb
console.log('testing')
$('.delete_distribution').bind('ajax:success', function() {
  console.log('deleting ...');
  $(this).closest('.run-cells-dis').fadeOut();
});

app/views/distributions/edit.html.erb
<body style="background-image: linear-gradient(to bottom right, var(--ysub) , #cbcbcb)">
  <div class="d-new">
    <h1>Update Distribution</h1>
    <%= render 'form' %>
  </div>
</body>

app/views/distributions/index.html.erb
<body style="background-image: linear-gradient(to bottom right, var(--ysub) , #cbcbcb)">

<h1 class="center"><strong>Distribution Drop Offs</h1></strong>
  <p class="center"><%= link_to 'Post a New Distribution', new_distribution_path %></p>
  <div class="run-grid">
      <% @distributions.each  do |g| %>
      <div class="run-cells-dis">
        Last Name: &emsp; &emsp;&emsp; <%= g.last_name %><br>
        First Name: &emsp; &emsp;&emsp;<%= g.first_name %><br>
        Phone: &emsp; &emsp; &emsp; &emsp;&ensp;<%= g.phone %><br>
        Drop Off Date: &emsp; <%= g.dropoff_date %> <br>
        Drop Off Time: &emsp; &nbsp<%= g.dropoff_time %> <br>
        Region: &emsp; &emsp; &ensp;&emsp; &ensp; <%= g.region %> <br>
        Drop Off<br>Location: &emsp; &emsp; &emsp; <%= g.dropoff_location %> <br>
        Distribution:  &emsp; &ensp;  <%= g.distribution %> <br>
        Runner: &emsp;&emsp; &emsp;&emsp; <%= g.runner.full_name if g.runner %> <br><br>
          <%= link_to "Edit", edit_distribution_path(g.id) %>
          <%= link_to "Delete", distribution_path(g),
                  method: :delete,
                  data: { confirm: 'Are you sure?', remote: true }, :class => "delete_distribution"  %><br>
</div>
      <% end %>
    </div>
</body>

app/views/distributions/new.html.erb
<div class="d-new">
<h1 class="indent">New Ditribution</h1>
<body class="newback">
    <%= render 'form' %>


</div>

app/views/distributions/show.html.erb
<body style="background-image: linear-gradient(to bottom right, var(--ysub) , #cbcbcb)">
<div class="d-new">
  <h1>Distribution</h1><br>
    <div>
      First Name: &emsp; &emsp;&ensp; <%= @distribution.first_name %> <br>
      Last Name: &emsp; &emsp;&emsp; <%= @distribution.last_name %> <br>
      Phone: &emsp; &emsp; &emsp; &emsp; <%= @distribution.phone %> <br>
      Drop Off Date: &emsp; <%= @distribution.dropoff_date %> <br>
      Drop Off Time: &emsp; <%= @distribution.dropoff_time %> <br>
      Region: &emsp; &emsp; &ensp;&emsp; &ensp; <%= @distribution.region %> <br>
      Drop Off <br>Location: &emsp; &emsp; &emsp; <%= @distribution.dropoff_location %> <br>
      Distribution: &emsp; &ensp; <%= @distribution.distribution %> <br>
      Runner: &emsp; &emsp;&emsp;&emsp; <%= Runner.find(@distribution.runner_id).full_name if @distribution.runner %> <br><br>
  </div>
<%= link_to "Edit", edit_distribution_path %>&emsp; &emsp;
<%= link_to "Index", distributions_path %>&emsp; &emsp;
<%= link_to "New", new_distribution_path %><br>
</div>
</body>