config/routes.rb
Rails.application.routes.draw do

root 'pages#home'

get 'register' => 'users#new'
  # post 'register' => 'users#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


  resources :users
  resources :donations
  resources :distributions
  resources :runners do
    resources :donations
    resources :distributions
  end

  get '/runners/pickup/:donation_id' => 'runners#pickup'
  get '/runners/dropoff/:distr_id' => 'runners#dropoff'

  get 'pages/about'
  get 'pages/help'

  # get 'pages/home'

  # get 'users/new'
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'

  # get 'donations/new'
  # get 'donations/edit'
  # get 'donations/show'
  # get 'donations/index'

  # get 'distributions/new'
  # get 'distributions/edit'
  # get 'distributions/show'
  # get 'distributions/index'

  # get 'runners/new'
  # get 'runners/edit'
  # get 'runners/show'
  # get 'runners/index'

  # get 'sessions/new'
  # get 'sessions/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<style>
  #map {
    height: 60vh;
    width: 60vw;
    margin-left: 20%;
    margin-top: 5%;
  }
</style>

<div id ="map"></div>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_ENV_KEY'] %>&callback=initMap">
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: <%= @distribution.latitude %>, lng: <%= @distribution.longitude %> },
      zoom: 17
    });

    var marker = new google.maps.Marker({
          map: map,
          position: {lat: <%= @distribution.latitude %>, lng: <%= @distribution.longitude %> },
          title: 'Hello World!'
        });
  }



</script>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
  <%if logged_in? %>
  <body class="lback">

    <h1 class="home-welcome">Hey, <%= "#{current_user.first_name}"%> Welcome back!</h1>
    <h1 class="home-welcome">Today I'll make an impact as a:</h1>
      <div class="desc-grid">

        <div class="l-click">
          <p><strong><%= link_to 'Donor', new_donation_path %></strong></p>
          <p class="desc"><%= link_to "Have food you'd like to donate?", new_donation_path %></p>
        </div>


        <div class="c-click">
          <p><strong><%= link_to 'Runner', new_runner_path %></strong></p>
          <p class="desc"><%= link_to "Willing to transport food?", new_runner_path %></p>
        </div>
        <div class="r-click">
          <p><strong><%= link_to 'Distributor', new_distribution_path %></strong></p>
          <p class="desc"><%= link_to "Availabe to Distribute food?", new_distribution_path %></p>
        </div>
      </div>
    <% else %>
    <body class="homeback">
      <h1 class="homepage ">Selfless</h1>
    <%end %>
  </div>
</body>