config/routes.rb
Rails.application.routes.draw do

root 'pages#home'

get 'register' => 'users#new'
  # post 'register' => 'users#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


  resources :users
  resources :donations
  resources :distributions
  resources :runners do
    resources :donations
    resources :distributions
  end

  get '/runners/pickup/:donation_id' => 'runners#pickup'
  get '/runners/dropoff/:distr_id' => 'runners#dropoff'

  get 'pages/about'
  get 'pages/help'

  # get 'pages/home'

  # get 'users/new'
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'

  # get 'donations/new'
  # get 'donations/edit'
  # get 'donations/show'
  # get 'donations/index'

  # get 'distributions/new'
  # get 'distributions/edit'
  # get 'distributions/show'
  # get 'distributions/index'

  # get 'runners/new'
  # get 'runners/edit'
  # get 'runners/show'
  # get 'runners/index'

  # get 'sessions/new'
  # get 'sessions/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :runner, required: false
  after_validation :geocode

  geocoded_by :pickup_location

  def full_name
   self.first_name + " " + self.last_name
  end

end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]

    def new
      @donation = Donation.new
      @runners = Runner.all
    end

    def index
      @runners = Runner.all
      @donations = Donation.all
    end

    def create
      @donation = Donation.new(donation_params)
      if @donation.save
        msg = "Your donation has been successfully created"
        p msg
        redirect_to @donation
      else
          msg = "There was an error in creating your donation.  Try again"
        p msg
        p @donation.errors.messages
        render 'new'
      end
    end


    def show
    end


    def update
      if @donation.update(donation_params)
        p 'Donation Successfully Updated!'
        redirect_to @donation
      else
        render 'edit'
      end
    end


    def edit
    end


    def destroy
        respond_to do |format|
          format.js
          format.html { p 'html response'; redirect_to root_path }
        end
        @donation.destroy
    end


  private

    def set_donation
        @donation = Donation.find(params[:id])
    end

    def donation_params
      params.require(:donation).permit(:first_name, :last_name, :email, :phone, :region, :pickup_location, :pickup_time, :pickup_date, :donation, :runner_id, :distribution_id, :password, :password_confirmation)
    end
  end

app/helpers/donations_helper.rb
module DonationsHelper
  def full_name
    self.first_name + " " + self.last_name
  end
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  First Name: &nbsp <%= f.text_field :first_name, placeholder: 'First Name', value: current_user.first_name, required: true %> <br>
  Last Name: &emsp;<%= f.text_field :last_name, placeholder: 'Last Name', value: current_user.last_name, required: true %><br>
  Phone: &emsp;&emsp;&emsp;<%= f.telephone_field :phone, placeholder: 'Phone Number', required: true  %><br>
  Pick Up Date: <%= f.date_field :pickup_date, required: true  %><br>
  Pick Up Time: <%= f.time_field :pickup_time, required: true  %><br>
  Region: &emsp;&emsp;&ensp;<%=f.select :region, [['North Queens'], ['South Queens'], ['Brooklyn'], ['Uptown'], ['Downtown'], ['Midtown'], ['Harlem'], ['Bronx'],['Staten Island']], :include_blank => true  %><br>
  Pick Up Location: &emsp;&emsp;&emsp;<%= f.text_area :pickup_location %><br>
  Donation Description: <%= f.text_area  :donation, placeholder: 'Please be specific so runner and distributor can porperly prepare', required: true %><br>
  Runner: <br>

  <br>
  <%= f.submit %>
<% end %>

app/views/donations/destroy.js.erb
console.log('testing')
$('.delete_donation').bind('ajax:success', function() {
  console.log('deleting ...');
  $(this).closest('.run-cells-don').fadeOut();
});

app/views/donations/edit.html.erb
<body style="background-image: linear-gradient(to bottom right, var(--ysub) , #cbcbcb)">
  <div class="d-new">
    <h1>Update Donation</h1>
    <%= render 'form' %>
  </div>
</body>

app/views/donations/index.html.erb
<body style="background-image: linear-gradient(to bottom right, var(--ysub) , #cbcbcb)">

  <h1 class="center"><strong>Donation Pickups</h1></strong>
    <p class="center"><%= link_to 'Post a New Donation', new_donation_path %></p>
    <div class="run-grid">
      <% @donations.each  do |d| %>
      <div class="run-cells-don">
        First Name: &emsp; &emsp;&emsp;<%= d.first_name %><br>
        Last Name: &emsp; &emsp;&emsp; <%= d.last_name %><br>
        Phone: &emsp; &emsp; &emsp; &emsp;&ensp;<%= d.phone %><br>
        Pick Up Date: &emsp;&emsp; <%= d.pickup_date %> <br>
        Pick Up Time: &emsp; &ensp; &nbsp <%= d.pickup_time %> <br>
        Region: &emsp; &emsp; &ensp;&emsp; &nbsp <%= d.region %> <br>
        Pick Up<br>Location: &emsp; &emsp; &ensp; <%= d.pickup_location %> <br>
        Donation: &emsp; &emsp; &ensp;<%= d.donation %> <br>
        Runner: &emsp;&emsp;&emsp;&emsp; <%= d.runner.full_name if d.runner %> <br><br>
          <%= link_to "Edit", edit_donation_path(d.id) %>
          <%= link_to "Delete", donation_path(d),
                  method: :delete,
                  data: { confirm: 'Are you sure?', remote: true }, :class => "delete_donation"  %><br>
      </div>
      <% end %>
      </div>
</body>

app/views/donations/new.html.erb
<div class="d-new">
<h1 class="indent">New Donation</h1>
<body class="newdonback"> 
    <%= render 'form' %>


</div>

app/views/donations/show.html.erb
<body style="background-image: linear-gradient(to bottom right, var(--ysub) , #cbcbcb)">
<div class="d-new">
  <h1>Donation</h1><br>
    <div>
    First Name: &emsp; &emsp; <%= @donation.first_name %> <br>
    Last Name:  &emsp; &emsp;&ensp;<%= @donation.last_name %> <br>
    Phone:  &emsp; &emsp; &emsp; &ensp;<%= @donation.phone %><br>
    Pick Up Date:  &emsp;&nbsp <%= @donation.pickup_date %> <br>
    Pick Up Time: &emsp; &nbsp <%= @donation.pickup_time %> <br>
    Region: &emsp; &emsp; &ensp;&emsp; &ensp;  <% @donation.region %> <br>
    Pick Up <br>Location:  &emsp; &emsp;&ensp; <%= @donation.pickup_location %> <br>
    Donation:  &emsp; &emsp;&ensp;<%= @donation.donation %> <br>
    Runner: &nbsp &nbsp&nbsp <%= Runner.find(@donation.runner_id).full_name if @donation.runner_id %> <br><br>
  </div>
  <%= link_to "Edit", edit_donation_path %> &emsp; &emsp;
  <%= link_to "Index", donations_path %> &emsp; &emsp;
  <%= link_to "New", new_donation_path %><br>
</div>
</body>