config/routes.rb
Rails.application.routes.draw do

root 'pages#home'

get 'register' => 'users#new'
  # post 'register' => 'users#show'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'


  resources :users
  resources :donations
  resources :distributions
  resources :runners do
    resources :donations
    resources :distributions
  end

  get '/runners/pickup/:donation_id' => 'runners#pickup'
  get '/runners/dropoff/:distr_id' => 'runners#dropoff'

  get 'pages/about'
  get 'pages/help'

  # get 'pages/home'

  # get 'users/new'
  # get 'users/index'
  # get 'users/show'
  # get 'users/edit'

  # get 'donations/new'
  # get 'donations/edit'
  # get 'donations/show'
  # get 'donations/index'

  # get 'distributions/new'
  # get 'distributions/edit'
  # get 'distributions/show'
  # get 'distributions/index'

  # get 'runners/new'
  # get 'runners/edit'
  # get 'runners/show'
  # get 'runners/index'

  # get 'sessions/new'
  # get 'sessions/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<div class="nav">
  <ul>
    <li><%= link_to 'Selfless', root_path %></li>
        <% if logged_in? %>
    <li style="float:right"><%= link_to "#{current_user.email}" %></li>
    <li style="float:right"><%= link_to 'Donate', donations_path %></li>
    <li style="float:right"><%= link_to 'Run', runners_path %></li>
    <li style="float:right"><%= link_to 'Distribute', distributions_path %></li>
    <li style="float:right"><%= link_to 'Log out', logout_path, method: :delete %></li>

        <% else %>
    <li style="float:right"><%= link_to 'Register', register_path %></li>
    <li style="float:right"><%= link_to 'Login', login_path %></li>
        <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ppp4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Assistant|Barlow|Barlow+Condensed|Barlow+Semi+Condensed|Catamaran|Heebo|Istok+Web|Julius+Sans+One|Krub|Molengo|PT+Sans+Caption|PT+Sans+Narrow|Pontano+Sans|Questrial" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render 'layouts/header' %>
    </div>
    <%= yield %>
  </body>
</html>